Fix: error: ‘_width’ was not declared in this scope
The error seamed to be occuring because I declared WrapPosition methods
as inline in the header file, but then I also defining them in the
.cpp file. This created some conflicts.